### ISSUE TITLE
After the memory fix I've noticed another warning/error in php log.

### ISSUE THREAD

**Issue by niel** [zeebinz/rarinfo#12]
PHP Notice:  Undefined index: method in /var/www/nzedb/libs/zeebinz/rarinfo/rarinfo.php on line 687

We're seeing segmentation faults in the RAR decoding and I'm wondering if this might be related.

**Comment by zeebinz** [comment]
Segfaults (usually relating to different PHP versions and loaded extensions) really needs an xdebug trace to debug, otherwise we're shooting in the dark. The notice shouldn't be related - but as always, a sample file that can trigger it is key to getting a quick solution.

As a point of reference, I have rarinfo in a long-running PHP worker and it has merrily chugged along without needing a restart for a good while now (Uptime: 161d 19h 23m 41s). So anything you can do to help me reproduce any issues on your side would be helpful. Sample files are the most important, though.

**Comment by niel** [comment]
Turns out this was only tangentially connected to RARInfo. ;-)
